### ISSUE TITLE
Cannot import the module

### ISSUE THREAD

**Issue by marcellonepitone** [ttm/music#10]
The line `import music` throws back a long error whose last lines are `
 File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer`
I don't understand where the problem is. Could you please help me? Thank you.

**Comment by junqingqiao** [comment]
I have the same issue.

**Comment by jcampecino** [comment]
I am encountering the same issue. No one's looking into this, it seems.

**Comment by ttm** [comment]
@marcellonepitone , @junqingqiao , @jcampecino , I have updated the package a few moments ago. Please try again and report here if you run into any issues. In summary, the numpy's `linspace` function now requires the number of elements to be an integer. It should be solved but I'll be happy to look further into it.

**Comment by marcellonepitone** [comment]
Thank you for looking into this. Should I uninstall the package and then install it again?
At the present time this is it throws back.
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import music
  File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\music\__init__.py", line 1, in <module>
    from .utils import H
  File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\music\utils.py", line 5, in <module>
    from . import core
  File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\music\core\__init__.py", line 1, in <module>
    from .functions import *
  File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\music\core\functions.py", line 275, in <module>
    foo = n.linspace(-1, 1, Lt/2, endpoint=False)
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Users\divel\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer`

**Comment by ttm** [comment]
should be resolved some time ago.

**Comment by ttm** [comment]
@marcellonepitone @junqingqiao @jcampecino — closing the loop on this properly, four years late.

Your traceback was precise and worth restating, because it was never really answered here:

```
File ".../music/core/functions.py", line 275, in <module>
    foo = n.linspace(-1, 1, Lt/2, endpoint=False)
TypeError: 'float' object cannot be interpreted as an integer
```

`Lt/2` is true division, so it produced a float, and `numpy.linspace` stopped accepting a float count. It failed **at import time**, in module-level code, which is why `import music` died rather than some particular function. Nothing you did was wrong and there was no workaround short of editing the installed file.

@marcellonepitone, you reported in January 2022 that it was still failing after the fix, and pasted the same traceback again. You got no reply, and the issue was closed seven months later with "should be resolved some time ago". You were right and it deserved better.

**Fixed, and now guarded.** That module-level code is gone. Beyond the fix itself, `tests/test_public_api.py` now calls every exported function with its documented defaults and asserts the result is finite — the sweep that would have caught this on the first CI run. The suite is 481 tests at 100% coverage, enforced, on Python 3.10 through 3.13.

```console
pip install -U music
```

```python
import music
music.write_wav_mono(music.note(440, 1), "a.wav")
```

Verified from a clean virtualenv on 1.1.1. If anything still breaks for you, please open a new issue — it will get an answer this time.
